# Generated by Django 5.2.14 on 2026-05-16 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='Kalit (slug)')),
                ('name_uz_latn', models.CharField(max_length=200, verbose_name='Nomi (lotin)')),
                ('name_uz_cyrl', models.CharField(max_length=200, verbose_name='Nomi (krill)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (рус)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Mukofot mansubligi',
                'verbose_name_plural': 'Mukofot mansubliklari',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('key', models.SlugField(help_text='URL slug. Masalan: theater_circus, education, cinema, ...', max_length=64, unique=True, verbose_name='Kalit (slug)')),
                ('name_uz_latn', models.CharField(max_length=200, verbose_name='Nomi (lotin)')),
                ('name_uz_cyrl', models.CharField(max_length=200, verbose_name='Nomi (krill)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (рус)')),
                ('icon', models.CharField(blank=True, help_text='Frontend DirectionIcon kalit: theater, education, heritage, cinema, concert', max_length=50, verbose_name='Ikon nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AwardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('key', models.SlugField(max_length=64, verbose_name='Kalit (slug)')),
                ('name_uz_latn', models.CharField(max_length=200, verbose_name='Nomi (lotin)')),
                ('name_uz_cyrl', models.CharField(max_length=200, verbose_name='Nomi (krill)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (рус)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='core.awardaffiliation', verbose_name='Mansubligi')),
            ],
            options={
                'verbose_name': 'Mukofot turi',
                'verbose_name_plural': 'Mukofot turlari',
                'ordering': ['affiliation', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AwardName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('key', models.SlugField(max_length=128, verbose_name='Kalit (slug)')),
                ('name_uz_latn', models.CharField(max_length=300, verbose_name='Nomi (lotin)')),
                ('name_uz_cyrl', models.CharField(max_length=300, verbose_name='Nomi (krill)')),
                ('name_ru', models.CharField(max_length=300, verbose_name='Название (рус)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='core.awardtype', verbose_name='Turi')),
            ],
            options={
                'verbose_name': 'Mukofot nomi',
                'verbose_name_plural': 'Mukofot nomlari',
                'ordering': ['type', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('nationality', models.CharField(blank=True, max_length=64, verbose_name='Millati')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sanasi")),
                ('birth_place', models.CharField(blank=True, max_length=200, verbose_name="Tug'ilgan joyi")),
                ('residence_place', models.CharField(blank=True, help_text="Xaritada marker shu manzilga qo'yiladi", max_length=200, verbose_name='Hozirgi yashash joyi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='representatives/', verbose_name='Surati')),
                ('position', models.CharField(blank=True, max_length=300, verbose_name='Egallab turgan lavozimi')),
                ('is_active', models.BooleanField(default=True, help_text="Olib tashlangan bo'lsa ham, ma'lumotlar saqlanadi", verbose_name='Faol')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='representatives', to='core.direction', verbose_name="Yo'nalishi")),
            ],
            options={
                'verbose_name': 'Vakil',
                'verbose_name_plural': 'Vakillar',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RepresentativeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yili')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='representative_awards', to='core.awardname', verbose_name='Mukofot')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative_awards', to='core.representative', verbose_name='Vakil')),
            ],
            options={
                'verbose_name': 'Vakil mukofoti',
                'verbose_name_plural': 'Vakil mukofotlari',
                'ordering': ['-year'],
            },
        ),
        migrations.AddField(
            model_name='representative',
            name='awards',
            field=models.ManyToManyField(blank=True, related_name='holders', through='core.RepresentativeAward', to='core.awardname', verbose_name='Mukofotlari'),
        ),
        migrations.AddConstraint(
            model_name='awardtype',
            constraint=models.UniqueConstraint(fields=('affiliation', 'key'), name='unique_type_per_affiliation'),
        ),
        migrations.AddConstraint(
            model_name='awardname',
            constraint=models.UniqueConstraint(fields=('type', 'key'), name='unique_name_per_type'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['direction', 'is_active'], name='core_repres_directi_483c12_idx'),
        ),
        migrations.AddIndex(
            model_name='representative',
            index=models.Index(fields=['gender'], name='core_repres_gender_597735_idx'),
        ),
    ]
