# Generated by Django 5.2.14 on 2026-05-16 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='academic_degree',
            field=models.CharField(blank=True, help_text='Masalan: "san\'atshunoslik fanlari nomzodi" yoki "Yo\'q"', max_length=200, verbose_name='Ilmiy darajasi (unvoni)'),
        ),
        migrations.AddField(
            model_name='representative',
            name='career_level',
            field=models.CharField(blank=True, max_length=100, verbose_name='Martaba darajasi'),
        ),
        migrations.AddField(
            model_name='representative',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mehnat faoliyati haqida qisqacha tavsifnoma'),
        ),
        migrations.AddField(
            model_name='representative',
            name='health',
            field=models.CharField(blank=True, choices=[('good', 'Yaxshi'), ('average', "O'rtacha"), ('poor', 'Qoniqarsiz'), ('deceased', 'Vafot etgan')], max_length=20, verbose_name="Sog'lig'i"),
        ),
        migrations.AddField(
            model_name='representative',
            name='health_problems',
            field=models.TextField(blank=True, verbose_name="Sog'ligidagi muammolar"),
        ),
        migrations.AddField(
            model_name='representative',
            name='languages',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chet tillarni bilishi'),
        ),
        migrations.AddField(
            model_name='representative',
            name='last_medical_treatment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Qachon tibbiy muolaja olgan'),
        ),
        migrations.AddField(
            model_name='representative',
            name='leadership_experience',
            field=models.CharField(blank=True, help_text='Masalan: "6 yil" yoki "Yo\'q"', max_length=50, verbose_name='Rahbarlik staji'),
        ),
        migrations.AddField(
            model_name='representative',
            name='leadership_positions',
            field=models.TextField(blank=True, verbose_name='Faoliyat yuritgan rahbarlik lavozimlari'),
        ),
        migrations.AddField(
            model_name='representative',
            name='marital_status',
            field=models.CharField(blank=True, help_text='Masalan: "Oilali, 2 nafar farzandi bor"', max_length=300, verbose_name='Oilaviy va ijtimoiy ahvoli'),
        ),
        migrations.AddField(
            model_name='representative',
            name='medical_checkup',
            field=models.CharField(blank=True, max_length=200, verbose_name="Tibbiy ko'rikdan o'tganligi (so'nggi 2 yilda)"),
        ),
        migrations.AddField(
            model_name='representative',
            name='specialty',
            field=models.CharField(blank=True, max_length=300, verbose_name='Mutaxassisligi'),
        ),
        migrations.AddField(
            model_name='representative',
            name='state_events',
            field=models.TextField(blank=True, verbose_name='Davlat tadbirlaridagi ishtiroki'),
        ),
        migrations.AddField(
            model_name='representative',
            name='total_experience',
            field=models.CharField(blank=True, help_text='Masalan: "33 yil"', max_length=50, verbose_name='Umumiy mehnat staji'),
        ),
        migrations.AddField(
            model_name='representative',
            name='training',
            field=models.CharField(blank=True, max_length=300, verbose_name="Malaka oshirganligi (so'nggi 2 yilda)"),
        ),
        migrations.AddField(
            model_name='representative',
            name='university',
            field=models.CharField(blank=True, help_text='Masalan: "1971 y. Toshkent teatr instituti (kunduzgi)"', max_length=300, verbose_name='Tamomlagan OTM'),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('relation', models.CharField(choices=[('father', 'Otasi'), ('mother', 'Onasi'), ('spouse', "Turmush o'rtog'i"), ('child', 'Farzandi'), ('other', 'Boshqa')], max_length=20, verbose_name='Qarindoshlik darajasi')),
                ('name', models.CharField(max_length=200, verbose_name='Ism sharifi')),
                ('info', models.CharField(blank=True, help_text='Masalan: "1910 yil, Toshkent shahri"', max_length=200, verbose_name="Tug'ilgan yili va joyi")),
                ('note', models.CharField(blank=True, help_text='Masalan: "Uy bekasi" yoki "1946 yil vafot etgan"', max_length=300, verbose_name="Qo'shimcha izoh")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='core.representative', verbose_name='Vakil')),
            ],
            options={
                'verbose_name': "Oila a'zosi",
                'verbose_name_plural': "Oila a'zolari",
                'ordering': ('representative', 'order', 'id'),
            },
        ),
    ]
