# Generated by Django 5.2.14 on 2026-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='first_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Ismi'),
        ),
        migrations.AddField(
            model_name='representative',
            name='first_name_uz_cyrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Ismi'),
        ),
        migrations.AddField(
            model_name='representative',
            name='first_name_uz_latn',
            field=models.CharField(max_length=100, null=True, verbose_name='Ismi'),
        ),
        migrations.AddField(
            model_name='representative',
            name='last_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Familiyasi'),
        ),
        migrations.AddField(
            model_name='representative',
            name='last_name_uz_cyrl',
            field=models.CharField(max_length=100, null=True, verbose_name='Familiyasi'),
        ),
        migrations.AddField(
            model_name='representative',
            name='last_name_uz_latn',
            field=models.CharField(max_length=100, null=True, verbose_name='Familiyasi'),
        ),
        migrations.AddField(
            model_name='representative',
            name='middle_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otasining ismi'),
        ),
        migrations.AddField(
            model_name='representative',
            name='middle_name_uz_cyrl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otasining ismi'),
        ),
        migrations.AddField(
            model_name='representative',
            name='middle_name_uz_latn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Otasining ismi'),
        ),
    ]
