# Generated by Django 5.2.14 on 2026-05-18 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_representative_first_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('soato', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='SOATO kodi')),
                ('slug', models.SlugField(blank=True, max_length=64, verbose_name='Slug')),
                ('name_uz_latn', models.CharField(max_length=200, verbose_name='Nomi (uz-latn)')),
                ('name_uz_cyrl', models.CharField(blank=True, max_length=200, verbose_name='Nomi (uz-cyrl)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (ru)')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ('region', 'name_uz_latn'),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('soato', models.CharField(help_text='Masalan: 1703 (Andijon), 1726 (Toshkent shahri)', max_length=10, primary_key=True, serialize=False, verbose_name='SOATO kodi')),
                ('slug', models.SlugField(blank=True, help_text="Frontend SVG xaritasi uchun, masalan: 'andijon', 'toshkent-shahri'", max_length=64, verbose_name='Slug (frontend xarita kaliti)')),
                ('name_uz_latn', models.CharField(max_length=150, verbose_name='Nomi (uz-latn)')),
                ('name_uz_cyrl', models.CharField(blank=True, max_length=150, verbose_name='Nomi (uz-cyrl)')),
                ('name_ru', models.CharField(blank=True, max_length=150, verbose_name='Nomi (ru)')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ('name_uz_latn',),
            },
        ),
        migrations.RemoveField(
            model_name='representative',
            name='residence_place_ru',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='residence_place_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='residence_place_uz_latn',
        ),
        migrations.AlterField(
            model_name='representative',
            name='residence_place',
            field=models.CharField(blank=True, help_text="Mahalladan tashqari aniqlashtirish: ko'cha, uy raqami", max_length=200, verbose_name="Yashash manzili (qo'shimcha)"),
        ),
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('tin', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='TIN kodi')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Mahalla kodi')),
                ('name_uz_latn', models.CharField(max_length=200, verbose_name='Nomi (uz-latn)')),
                ('name_uz_cyrl', models.CharField(blank=True, max_length=200, verbose_name='Nomi (uz-cyrl)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (ru)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Nomi (en)')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahallas', to='core.district', verbose_name='Tumani')),
            ],
            options={
                'verbose_name': 'Mahalla',
                'verbose_name_plural': 'Mahallalar',
                'ordering': ('district', 'name_uz_latn'),
            },
        ),
        migrations.AddField(
            model_name='representative',
            name='residence_mahalla',
            field=models.ForeignKey(blank=True, help_text="Viloyat → tuman → mahalla tanlanadi. Xaritada marker shu tumanga qo'yiladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='core.mahalla', verbose_name='Hozirgi yashash joyi (mahalla)'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.region', verbose_name='Viloyati'),
        ),
        migrations.AddIndex(
            model_name='mahalla',
            index=models.Index(fields=['district'], name='core_mahall_distric_83dd8b_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['region'], name='core_distri_region__a89007_idx'),
        ),
    ]
