# Generated by Django 5.2.14 on 2026-05-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_representative_academic_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('code', models.SlugField(max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Til',
                'verbose_name_plural': 'Tillar',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.RemoveField(
            model_name='representative',
            name='languages',
        ),
        migrations.AlterField(
            model_name='representative',
            name='nationality',
            field=models.CharField(blank=True, choices=[('ozbek', "O'zbek"), ('qozoq', 'Qozoq'), ('tojik', 'Tojik'), ('rus', 'Rus'), ('qoraqalpoq', 'Qoraqalpoq'), ('qirgiz', "Qirg'iz"), ('turkman', 'Turkman'), ('tatar', 'Tatar'), ('koreys', 'Koreys'), ('uygur', "Uyg'ur"), ('ukrain', 'Ukrain'), ('belorus', 'Belorus'), ('armani', 'Armani'), ('ozarbayjon', 'Ozarbayjon'), ('yahudiy', 'Yahudiy'), ('bashqird', 'Bashqird'), ('chuvash', 'Chuvash'), ('lazgin', 'Lazgin'), ('dungan', 'Dungan'), ('turk', 'Turk'), ('arab', 'Arab'), ('eron', 'Eron'), ('afgon', "Afg'on"), ('hind', 'Hind'), ('boshqa', 'Boshqa')], max_length=30, verbose_name='Millati'),
        ),
        migrations.AddField(
            model_name='representative',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='speakers', to='core.language', verbose_name='Chet tillarni bilishi'),
        ),
    ]
