# Generated by Django 5.2.14 on 2026-05-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Centroid kenglik (lat)'),
        ),
        migrations.AddField(
            model_name='district',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Centroid uzunlik (lng)'),
        ),
    ]
