# Generated by Django 5.2.14 on 2026-05-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_district_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('title', models.CharField(help_text='Masalan: "Siyosiy partiyalar uchun"', max_length=200, verbose_name='Sarlavha')),
                ('title_uz_latn', models.CharField(help_text='Masalan: "Siyosiy partiyalar uchun"', max_length=200, null=True, verbose_name='Sarlavha')),
                ('title_uz_cyrl', models.CharField(help_text='Masalan: "Siyosiy partiyalar uchun"', max_length=200, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(help_text='Masalan: "Siyosiy partiyalar uchun"', max_length=200, null=True, verbose_name='Sarlavha')),
                ('icon', models.ImageField(help_text='Tavsiya: SVG, taxminan 64x64 px', upload_to='info_cards/icons/', verbose_name='Ikon (SVG yoki PNG)')),
                ('body', models.TextField(help_text="Pop-up oynada ko'rsatiladigan to'liq matn", verbose_name='Matni')),
                ('body_uz_latn', models.TextField(help_text="Pop-up oynada ko'rsatiladigan to'liq matn", null=True, verbose_name='Matni')),
                ('body_uz_cyrl', models.TextField(help_text="Pop-up oynada ko'rsatiladigan to'liq matn", null=True, verbose_name='Matni')),
                ('body_ru', models.TextField(help_text="Pop-up oynada ko'rsatiladigan to'liq matn", null=True, verbose_name='Matni')),
                ('order', models.PositiveIntegerField(default=0, help_text="Kichik raqam birinchi ko'rinadi", verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Info kartochka',
                'verbose_name_plural': 'Info kartochkalar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
