# Generated by Django 5.2.14 on 2026-05-20 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_infocard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocard',
            name='icon',
            field=models.FileField(help_text='SVG (tavsiya etiladi) yoki PNG. Taxminan 64x64 px', upload_to='info_cards/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Ikon (SVG, PNG, JPG)'),
        ),
    ]
