# Generated by Django 5.2.14 on 2026-05-25 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_infocard_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representative',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='birth_place_ru',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='birth_place_uz_cyrl',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='birth_place_uz_latn',
        ),
        migrations.AddField(
            model_name='representative',
            name='birth_mahalla',
            field=models.ForeignKey(blank=True, help_text='Viloyat → tuman → mahalla tanlanadi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='born_residents', to='core.mahalla', verbose_name="Tug'ilgan joyi (mahalla)"),
        ),
    ]
