# Generated by Django 5.2.14 on 2026-06-08 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_representative_district_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='birth_place_foreign',
            field=models.CharField(blank=True, help_text='Chet elda tug\'ilgan bo\'lsa, shu yerga qo\'lda yozing (masalan: "Moskva, Rossiya"). Viloyat/tuman tanlamang.', max_length=300, verbose_name="Tug'ilgan joyi (O'zbekistondan tashqarida)"),
        ),
        migrations.AddField(
            model_name='representative',
            name='residence_place_foreign',
            field=models.CharField(blank=True, help_text='Chet elda yashasa, shu yerga qo\'lda yozing (masalan: "Berlin, Germaniya"). Viloyat/tuman tanlamang.', max_length=300, verbose_name="Yashash joyi (O'zbekistondan tashqarida)"),
        ),
        migrations.AlterField(
            model_name='representative',
            name='birth_district',
            field=models.ForeignKey(blank=True, help_text="O'zbekistondan tug'ilgan bo'lsa: viloyat → tuman tanlanadi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='born_residents', to='core.district', verbose_name="Tug'ilgan joyi (tuman)"),
        ),
        migrations.AlterField(
            model_name='representative',
            name='residence_district',
            field=models.ForeignKey(blank=True, help_text="O'zbekistonda yashasa: viloyat → tuman tanlanadi. Xaritada marker shu tumanga qo'yiladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='core.district', verbose_name='Hozirgi yashash joyi (tuman)'),
        ),
    ]
